#ifndef KEYBOARDS_NRF52_SEPARATE_TEST_
#define KEYBOARDS_NRF52_SEPARATE_TEST_

#include "custom_board.h"

#define THIS_DEVICE_ROWS 4
#define THIS_DEVICE_COLS 7

#define MATRIX_ROW_PINS { PIN1, PIN2, PIN10, PIN11 }
#define MATRIX_COL_PINS { PIN20, PIN19, PIN18, PIN17, PIN16, PIN15, PIN14 }

#define IS_LEFT_HAND  false

#endif /* KEYBOARDS_NRF52_SEPARATE_TEST_ */
